"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "Meals",
      [
        {
          title: "Bacon-Ranch Chicken",
          description: "Not authentically Mexican in the slightest, but holy buckets are they good!",
          location: "Copenhagen",
          price: 180,
          max_seats: 12,
          available_seats: 6,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Coconut Curry Soup",
          description: "The best curry soup with chicken and coconut! ",
          location: "London",
          price: 120,
          max_seats: 16,
          available_seats: 12,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Roasted Cauliflower Soup",
          description: "I love making homemade soups in the fall, and this is my new favorite.",
          location: "Berlin",
          price: 170,
          max_seats: 11,
          available_seats: 7,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Oven-Roasted Asparagus",
          description: "Salty and savory, the roasting method kills the natural bitterness of asparagus.",
          location: "Paris",
          price: 110,
          max_seats: 12,
          available_seats: 8,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Homemade Mac & Cheese",
          description: "This is a nice rich mac and cheese. Serve with a salad for a great meatless dinner.",
          location: "Oslo",
          price: 160,
          max_seats: 12,
          available_seats: 0,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Juicy Roasted Chicken",
          description: "I never have had a chicken this juicy before,this little trick works.",
          location: "New York",
          price: 90,
          max_seats: 12,
          available_seats: 12,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Salmon Patties",
          description: "These salmon patties are delicious for lunch or dinner.",
          location: "Hamburg",
          price: 160,
          max_seats: 16,
          available_seats: 0,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Chicken Pot Pie",
          description: "A delicious chicken pie made from scratch with carrots, peas and celery.",
          location: "Copenhagen",
          price: 170,
          max_seats: 12,
          available_seats: 12,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Classic Roast Lamb",
          description: "Just as easy, if not easier than roasting a chicken.",
          location: "Copenhagen",
          price: 190,
          max_seats: 12,
          available_seats: 12,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Mushroom Bolognese",
          description: "Probably the world's best meal.",
          location: "Copenhagen",
          price: 130,
          max_seats: 6,
          available_seats: 6,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Winter Minestrone",
          description: "A delicious minestrone, something delicious.",
          location: "Copenhagen",
          price: 110,
          max_seats: 12,
          available_seats: 0,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          title: "Chicken Piccata",
          description: "You have not tasted a chicken that was better.",
          location: "Copenhagen",
          price: 140,
          max_seats: 12,
          available_seats: 12,
          date: "2022-01-25 09:04:59",
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("Meals", null, {});
  },
};
